services:
  redis:
    profiles:
      - redis
    image: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
  bot:
    build: .
    image: musicboy-redux:latest
    restart: unless-stopped
    env_file: .env
